apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prom
spec:
  serviceAccountName: nfs-client-provisioner
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-storage