apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc_prom
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: slow