kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: slow
  annotations:
  - name: storageclass.kubernetes.io/is-default-class
    value: true
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard