apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  namespace: weave
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: scope.wyc.cn
    http:
      paths:
      - backend:
          serviceName: weave-scope-app
          servicePort: 80