apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9308"
      labels:
        app: kafka-exporter
    spec:
      containers:
      - name: metrics
        image: danielqsj/kafka-exporter
        command:
          - kafka_exporter --kafka.server=10.1.0.11:9092 --kafka.server=10.1.0.12:9092 --kafka.server=10.1.0.13:9092
        ports:
        - containerPort: 9308