apiVersion: extensions/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: monitor
  name: monitor
spec:
  selector:
    matchLabels:
      app: monitor
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        # image: xiaoyaolang/o_log_monitor
        image: xiaoyaolang/o_log_monitor:test
        imagePullPolicy: Always
        # imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: monitor-conf
          mountPath: "/home/conf/"
        # command:
        #   - "/home/monitor"

      volumes:
      - name: monitor-conf
        configMap:
          name: olog-config-map
          items:
            - key: monitor.xml
              path: monitor.xml
      
      
