apiVersion: extensions/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: order
  name: order
spec:
  selector:
    matchLabels:
      app: order
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        # image: xiaoyaolang/o_log_order
        image: xiaoyaolang/o_log_order:test
        imagePullPolicy: Always
        # imagePullPolicy: IfNotPresent
        env:
        - name: WORKER_NUMBER
          value: "1"
        - name: KAFKA_BROKER
          value: "10.1.0.11:9092"