apiVersion: extensions/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: elk
  name: elk
spec:
  selector:
    matchLabels:
      app: elk
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: elk
    spec:
      nodeSelector:
        kubernetes.io/hostname: node-2
      initContainers:
      - name: set-vm-max-map-count
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sysctl', '-w', 'vm.max_map_count=262144']
        securityContext:
          privileged: true
      containers:
      - name: elk
        image: sebp/elk
        # image: xiaoyaolang/o_log_simulator
        # imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5601
        - containerPort: 9200
        - containerPort: 9600
        volumeMounts:
        - name: logstash-yml
          mountPath: "/opt/logstash/config/logstash.yml"
          subPath: "logstash.yml"
        - name: logstash-conf
          mountPath: "/etc/logstash/conf.d"

      volumes:
      - name: logstash-conf
        configMap:
          name: elk-config-map
          items:
            - key: logstash.conf
              path: logstash.conf
      - name: logstash-yml
        configMap:
          name: elk-config-map
          items:
            - key: logstash.yml
              path: logstash.yml

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
  - port: 5601
    nodePort: 30301
  selector:
    app: elk

---
apiVersion: v1
kind: Service
metadata:
  name: elk
spec:
  ports:
  - name: elastic
    port: 9200
  - name: logstash
    port: 9600
  selector:
    app: elk