apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: grafana.wyc.cn
    http:
      paths:
      - backend:
          serviceName: default:graf-grafana
          servicePort: 80