apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: kibana.wyc.cn
    http:
      paths:
      - backend:
          serviceName: kibana
          servicePort: 5601